# fly.toml app configuration file generated for fastapi-101 on 2023-08-06T10:09:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fastapi-101"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
